package mastermind;

import code.*;
import utils.*;

// Class of the game. Responsibility of UI and principal function
public class Mastermind {
    private final Code secretCode;  // Code generated by CPU
    private final Code playerCode;  // Code received from input by player
    private int attempts;   // Current player attempt
    private boolean isFind; // Flag for end loop of attempts

    public Mastermind() {
        this.secretCode = new Code();
        this.playerCode = new Code();
        this.attempts = 0;
        this.isFind = false;
    }

    // Main menu and core of the game
    public void play() {
        System.out.println("<--------------------[ MASTERMIND ]-------------------->");
        System.out.println("Welcome to Mastermind game! In this version, you will compete\n" +
                           "against the CPU. The CPU will generate a code composed by "
                           + GameConstants.MAX_CODE_LENGTH + " numbers.\n" +
                           "Allowed values: 0, 1, 2, 3, 4, 5. Same values are allowed.\n" +
                           "You have " + GameConstants.ATTEMPTS + " " +
                           "attempts. After each try a feedback will tell you what's correct:\n" +
                           "X correct position, Y correct number but wrong position.\n");
        System.out.print("CPU is creating the code... ");
        generateCode(); // CPU generating code
        System.out.println("code generated!");

        System.out.println("Now you have to find the code. Good luck!\n");
        findSecretCode();   // Loop for attempts

        if (this.isFind)    // End game, check flag isFind
            System.out.println("Congratulation, you win! Thanks for playing.");
        else
            System.out.println("Nice try, but you did not find the code.\n" +
                               "Secret code: " + this.secretCode.toString());
    }

    // Code is generated from a pool of integer values. ReadRandom is a custom class used for generating random numbers
    // of any type
    private void generateCode() {
        ReadRandom readRandom = new ReadRandom();

        while (this.secretCode.size() != GameConstants.MAX_CODE_LENGTH)
            secretCode.add(new Digit(readRandom.readInt(6)));
    }

    // Player turn. The player has to find the code
    private void findSecretCode() {
        Read input = new Read();    // Custom class for input from keyword
        while (this.attempts < GameConstants.ATTEMPTS && !this.isFind) {
            System.out.println("<----------[ ATTEMPT " + (this.attempts + 1) + "]---------->");
            readCode(input);    // Player guessed code is read and checked if contains any errors
            checkPlayerCode();  // Check if the player code equals with the CPU one
        }
    }

    private void checkPlayerCode() {
        // If the codes are the same, the game is finished by setting true the flag
        // If it's false, checkOccurrences will set the feedback
        if (playerCode.equals(secretCode))
            this.isFind = true;
        else {
            this.playerCode.checkOccurrences(this.secretCode);
            System.out.println("Feedback: " + this.playerCode.getFeedback());

            // Clearing the digits of the player code
            this.playerCode.clear();
            this.attempts++;    // Incrementing the attempts
        }
    }

    // Player insert a string. The string is converted to an array of char and then processed
    // to verify if it contains invalid values
    private void readCode(Read input) {
        boolean isValid = true;
        do {
            System.out.print("Insert your code: ");
            String code = input.readString();

            char[] charArray = code.toCharArray();
            for (char c : charArray) {
                int singleDigit = Integer.parseInt(String.valueOf(c));

                if (singleDigit < 0 || singleDigit > 5)
                    isValid = false;
                else
                    playerCode.add(new Digit(singleDigit)); // Everything OK, add digit to the code
            }
        } while (!isValid);
    }

}
